name: '6 Hours Farm XP'
run-name: 'Your study script is running! Click me to see its progress.'

on:
  schedule:
    - cron: '* */6 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - run: npm install node-fetch
        

      - run: node xp.js
        env:
          lessonsToComplete: 9999999999
          token: ${{ secrets.TOKEN }}
          userId: ${{ secrets.USER_ID }}
